 const SAVE_SELECED_PAGE = 'SAVE_SELECED_PAGE'
 const CHANGE_SELECTED_CONTENT = 'CHANGE_SELECTED_CONTENT'
 const SAVE_PAGE_EDIT_DATA = 'SAVE_PAGE_EDIT_DATA'
 const SAVE_PAGE_ADD_DATA = 'SAVE_PAGE_ADD_DATA'

export {
    SAVE_SELECED_PAGE,
    SAVE_PAGE_EDIT_DATA,
    CHANGE_SELECTED_CONTENT,
    SAVE_PAGE_ADD_DATA
}